# Generated by Django 5.2.6 on 2025-09-11 10:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("male", "Male"),
                            ("female", "Female"),
                            ("other", "Other"),
                        ],
                        max_length=10,
                    ),
                ),
                ("age", models.PositiveIntegerField()),
                (
                    "physical_id_type",
                    models.CharField(
                        choices=[
                            ("aadhar", "Aadhar"),
                            ("passport", "Passport"),
                            ("driver_license", "Driver License"),
                            ("college_id", "College ID"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("physical_id_photo", models.ImageField(upload_to="physical_ids/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
