# Generated by Django 5.2.6 on 2026-03-20 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PigaApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=300)),
                ('date', models.DateField()),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('organisation', models.CharField(max_length=300)),
                ('elevator_pitch', models.TextField(help_text='Brief elevator pitch of the idea')),
                ('team', models.TextField(help_text='Team members and their roles')),
                ('problem_opportunity', models.TextField(help_text='Problem or opportunity being addressed')),
                ('solution_technology', models.TextField(help_text='Proposed solution or technology')),
                ('current_status', models.TextField(help_text='Current status or stage of the project')),
                ('unique_value_proposition', models.TextField(help_text='What makes this unique')),
                ('cost_budget', models.TextField(help_text='Cost and budget bifurcation')),
                ('key_metrics', models.TextField(help_text='Key metrics and validation data')),
                ('customer_segments', models.TextField(help_text='Customer segments and market size')),
                ('twelve_month_plan', models.TextField(help_text='12-month execution plan')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('UNDER_REVIEW', 'Under Review'), ('REVIEW_BACK', 'Sent Back for Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('review_feedback', models.TextField(blank=True, help_text='Admin feedback when sending back for review or rejecting', null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='piga_applications', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='piga_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['status', 'submitted_at'], name='piga_pigaap_status_6908bc_idx'), models.Index(fields=['applicant', 'status'], name='piga_pigaap_applica_9c5715_idx')],
            },
        ),
    ]
