# Generated by Django 5.1.1 on 2025-09-28 20:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0002_remove_service_availability_map_servicerequest_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="service",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="servicerequest",
            options={"ordering": ["-requested_at"]},
        ),
        migrations.AddIndex(
            model_name="availability",
            index=models.Index(
                fields=["service", "day_of_week"], name="services_av_service_c4c986_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="servicerequest",
            index=models.Index(
                fields=["status", "requested_at"], name="services_se_status_fedf3c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="servicerequest",
            index=models.Index(
                fields=["requested_by", "status"], name="services_se_request_16e695_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="servicerequest",
            index=models.Index(
                fields=["service", "status"], name="services_se_service_a7707a_idx"
            ),
        ),
    ]
