# Generated by Django 5.2.6 on 2025-10-01 20:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "services",
            "0003_alter_service_options_alter_servicerequest_options_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="parallel_lines",
            field=models.PositiveIntegerField(
                default=1, help_text="How many requests can be served in parallel"
            ),
        ),
        migrations.AddField(
            model_name="servicerequest",
            name="availability",
            field=models.ForeignKey(
                blank=True,
                help_text="The availability slot this request is scheduled in",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requests",
                to="services.availability",
            ),
        ),
        migrations.AddField(
            model_name="servicerequest",
            name="scheduled_end",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="servicerequest",
            name="scheduled_start",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="service",
            name="admin",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="services",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
