# Generated by Django 5.2.6 on 2025-10-01 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "services",
            "0004_service_parallel_lines_servicerequest_availability_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="availability",
            name="status",
            field=models.CharField(
                choices=[
                    ("OPERATIONAL", "Operational"),
                    ("DOWN", "Down"),
                    ("MAINTENANCE", "Maintenance"),
                ],
                default="OPERATIONAL",
                max_length=20,
            ),
        ),
    ]
