# Generated by Django 5.1.1 on 2025-12-16 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_availability_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='status',
        ),
        migrations.RemoveField(
            model_name='service',
            name='parallel_lines',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='scheduled_end',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='scheduled_start',
        ),
    ]
